//! Deliberately restricted stock-U Linux launch inputs. No discovery/fallback.
use std::collections::BTreeMap;
use std::io::BufRead;
use std::path::{Path, PathBuf};

use anyhow::{ensure, Context};
use serde::{Deserialize, Serialize};

use crate::agent_management::{file_sha256, ExplicitLaunchContract};
use crate::role_revision::Sha256;
use crate::session::model::{CutexSessionRecord, CutexSessionRuntimeBackend, CutexSessionStore};

pub const STOCK_COMMIT: &str = "3d2ee51ca2d5db578f328aa75e20aa22c0197c9a";
pub const STOCK_EXECUTABLE_SHA256: &str =
    "56ef98ab4032d317ab26e9b5e5a175650717351edb16ed9cde0cb6d1734d62da";
pub const STOCK_HOST_SHA256: &str =
    "3e85d67471825f73d02ff5f7e047ca1f6ca8caa3f59e4c6e8d9ca6ca7302cb45";
pub const STOCK_SCHEMA_SHA256: &str =
    "b06f77062369d481a59cc70720c12b89cb9dd49c385863923262102d3ad6c978";

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct VerifiedFile {
    pub path: PathBuf,
    pub sha256: Sha256,
}
impl VerifiedFile {
    pub fn validate(&self) -> anyhow::Result<()> {
        canonical(&self.path)?;
        ensure!(self.path.is_file(), "stock reference is not a file");
        ensure!(
            file_sha256(&self.path)? == self.sha256,
            "stock reference changed"
        );
        Ok(())
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StockBundle {
    pub version: u32,
    pub upstream_commit: String,
    pub executable: VerifiedFile,
    pub code_mode_host: VerifiedFile,
    pub facade: VerifiedFile,
    /// Generated by this pinned executable with --experimental.
    pub schema: VerifiedFile,
    /// The authoritative shared config is reviewed, never rewritten on launch.
    pub shared_config: VerifiedFile,
}
impl StockBundle {
    pub fn load(contract: &ExplicitLaunchContract) -> anyhow::Result<Self> {
        contract.validate()?;
        let bundle: Self = serde_json::from_slice(&std::fs::read(&contract.bundle_manifest)?)
            .context("invalid stock bundle manifest")?;
        ensure!(cfg!(target_os = "linux"), "stock subset requires Linux");
        ensure!(
            bundle.version == 1 && bundle.upstream_commit == STOCK_COMMIT,
            "unsupported stock bundle version/source"
        );
        ensure!(
            bundle.executable.sha256.as_str() == STOCK_EXECUTABLE_SHA256,
            "unpinned stock executable"
        );
        ensure!(
            bundle.code_mode_host.sha256.as_str() == STOCK_HOST_SHA256
                && bundle.schema.sha256.as_str() == STOCK_SCHEMA_SHA256,
            "unpinned stock companion/schema"
        );
        for file in [
            &bundle.executable,
            &bundle.code_mode_host,
            &bundle.facade,
            &bundle.schema,
            &bundle.shared_config,
        ] {
            file.validate()?;
        }
        ensure!(
            bundle.code_mode_host.path
                == bundle
                    .executable
                    .path
                    .parent()
                    .context("stock binary parent missing")?
                    .join("codex-code-mode-host"),
            "stock companion must be beside executable"
        );
        ensure!(
            bundle.shared_config.path == contract.native_home.join("config.toml"),
            "wrong shared config/home"
        );
        let schema: serde_json::Value =
            serde_json::from_slice(&std::fs::read(&bundle.schema.path)?)?;
        ensure!(schema.is_object(), "invalid stock protocol schema");
        validate_shared_config(&std::fs::read_to_string(&bundle.shared_config.path)?)?;
        Ok(bundle)
    }
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct SharedConfig {
    #[serde(default)]
    projects: BTreeMap<String, Trust>,
    analytics: Option<Analytics>,
    notice: Option<Notice>,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Trust {
    trust_level: String,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Analytics {
    enabled: bool,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Notice {
    #[serde(default)]
    model_migrations: BTreeMap<String, String>,
}
pub fn validate_shared_config(raw: &str) -> anyhow::Result<()> {
    let config: SharedConfig = toml::from_str(raw).map_err(|_| anyhow::anyhow!("unsupported shared stock config; only reviewed trust/notices and disabled analytics are supported"))?;
    ensure!(
        config
            .projects
            .values()
            .all(|p| matches!(p.trust_level.as_str(), "trusted" | "untrusted")),
        "unsupported stock trust level"
    );
    ensure!(
        config.analytics.is_none_or(|a| !a.enabled),
        "stock private analytics must be disabled"
    );
    if let Some(notice) = config.notice {
        ensure!(
            notice
                .model_migrations
                .iter()
                .all(|(a, b)| !a.is_empty() && !b.is_empty()),
            "invalid stock migration notice"
        );
    }
    Ok(())
}

pub fn canonical(path: &Path) -> anyhow::Result<()> {
    ensure!(
        path.is_absolute() && path.canonicalize()? == path,
        "canonical existing stock path required"
    );
    Ok(())
}

/// Current nonsecret configuration, bound separately from durable identity.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StockConfiguration {
    pub profile_name: String,
    pub profile_id: String,
    pub inherited: bool,
    pub profile_sha256: Sha256,
    pub account_sha256: Sha256,
    pub model: String,
    pub reasoning: Option<String>,
    pub model_provider: String,
    pub provider: DummyProvider,
    pub sandbox: String,
    pub approval: String,
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct DummyProvider {
    pub name: String,
    pub base_url: String,
    pub wire_api: String,
    pub requires_openai_auth: bool,
    pub supports_websockets: bool,
}
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct ProfileConfig {
    model: String,
    model_provider: String,
    model_reasoning_effort: Option<String>,
    model_providers: BTreeMap<String, DummyProvider>,
}

pub fn current_configuration(record: &CutexSessionRecord) -> anyhow::Result<StockConfiguration> {
    use crate::profiles::model::{AccountsStore, CliKind, RuntimeConfig};
    ensure!(
        record.default_cli_args.is_empty(),
        "stock does not accept arbitrary durable CLI overrides"
    );
    let config = crate::config::store::load_codez_config_checked()?;
    let inherited = record.profile.is_none();
    let name = record
        .profile
        .as_ref()
        .or(config.default_profile.as_ref())
        .context("stock inherited profile unavailable; explicit current default required")?;
    ensure!(!name.trim().is_empty(), "stock profile is empty");
    // Read current store without canonicalizing, selecting another account or writing it.
    let raw_accounts: serde_json::Value =
        serde_json::from_slice(&std::fs::read(crate::config::paths::accounts_path()?)?)?;
    ensure!(
        raw_accounts.as_object().is_some_and(|o| o
            .keys()
            .all(|k| matches!(k.as_str(), "version" | "accounts" | "active_account_id"))),
        "unsupported stock account store fields"
    );
    let raw_entries = raw_accounts["accounts"]
        .as_array()
        .context("invalid stock account store")?;
    for entry in raw_entries
        .iter()
        .filter(|a| a["name"].as_str() == Some(name))
    {
        ensure!(
            entry.as_object().is_some_and(|o| o.keys().all(|k| matches!(
                k.as_str(),
                "id" | "name"
                    | "email"
                    | "plan_type"
                    | "source"
                    | "runtime"
                    | "proxy"
                    | "session"
                    | "cli_kind"
                    | "default_cli_args"
                    | "agent_name"
                    | "last_used_at"
            ))),
            "unsupported stock account fields"
        );
    }
    let accounts: AccountsStore = serde_json::from_value(raw_accounts)?;
    ensure!(
        accounts.version == crate::profiles::model::STORE_VERSION,
        "unsupported stock account store version"
    );
    let matches: Vec<_> = accounts
        .accounts
        .iter()
        .filter(|a| &a.name == name)
        .collect();
    ensure!(matches.len() == 1, "stock profile missing or ambiguous");
    let account = matches[0];
    ensure!(
        uuid::Uuid::parse_str(&account.id)?.to_string() == account.id,
        "stock profile id must be an exact UUID"
    );
    ensure!(
        matches!(account.runtime, RuntimeConfig::Host)
            && account.cli_kind == CliKind::Codex
            && account.proxy.is_none()
            && account.session.is_none()
            && account.default_cli_args.is_empty(),
        "unsupported stock account/runtime/options"
    );
    ensure!(
        account.email.is_none() && account.plan_type.is_none(),
        "real account authentication is unsupported by private stock subset"
    );
    let files = crate::profiles::materialize::materialized_account_files(account)?;
    ensure!(
        !files.auth_path.try_exists()?,
        "stock private subset does not consume profile auth files"
    );
    canonical(&files.config_path)?;
    let raw = std::fs::read_to_string(&files.config_path)?;
    let profile: ProfileConfig = toml::from_str(&raw)
        .map_err(|_| anyhow::anyhow!("unsupported stock profile configuration"))?;
    ensure!(
        profile.model_providers.len() == 1,
        "exactly one dummy provider required"
    );
    let provider = profile
        .model_providers
        .get(&profile.model_provider)
        .context("configured provider missing")?
        .clone();
    let url = url::Url::parse(&provider.base_url)?;
    ensure!(
        url.scheme() == "http"
            && matches!(url.host_str(), Some("127.0.0.1") | Some("[::1]"))
            && url.username().is_empty()
            && url.password().is_none()
            && url.query().is_none()
            && !provider.requires_openai_auth
            && !provider.supports_websockets
            && provider.wire_api == "responses",
        "only private loopback unauthenticated fake Responses provider is supported"
    );
    let (sandbox, approval) = crate::runtime::args::effective_runtime_permission_defaults(record);
    let sandbox = sandbox.context("explicit stock sandbox required")?;
    ensure!(
        matches!(
            sandbox.as_str(),
            "read-only" | "workspace-write" | "danger-full-access"
        ),
        "unsupported stock sandbox"
    );
    // Approval remains explicit: do not silently turn full access into never.
    ensure!(
        record.approval_policy.is_some(),
        "explicit stock approval policy required"
    );
    let approval = approval.context("explicit stock approval policy required")?;
    ensure!(
        matches!(approval.as_str(), "untrusted" | "on-request" | "never"),
        "unsupported stock approval policy"
    );
    if let Some(permission) = &record.permission_defaults {
        ensure!(
            matches!(
                (permission.as_str(), sandbox.as_str()),
                ("read-only", "read-only")
                    | ("workspace", "workspace-write")
                    | ("full-access", "danger-full-access")
            ),
            "unknown or inconsistent stock permission alias"
        );
    }
    let model = record.model_defaults.clone().unwrap_or(profile.model);
    ensure!(
        !model.trim().is_empty() && !model.chars().any(char::is_control),
        "invalid stock model"
    );
    let reasoning = record
        .reasoning_defaults
        .clone()
        .or(profile.model_reasoning_effort);
    ensure!(
        reasoning
            .as_deref()
            .is_none_or(|r| matches!(r, "none" | "minimal" | "low" | "medium" | "high" | "xhigh")),
        "unsupported stock reasoning"
    );
    use sha2::Digest;
    Ok(StockConfiguration {
        profile_name: name.clone(),
        profile_id: account.id.clone(),
        inherited,
        profile_sha256: file_sha256(&files.config_path)?,
        account_sha256: Sha256::new(format!(
            "{:x}",
            sha2::Sha256::digest(serde_json::to_vec(account)?)
        ))
        .map_err(|_| anyhow::anyhow!("invalid account digest"))?,
        model,
        reasoning,
        model_provider: profile.model_provider,
        provider,
        sandbox,
        approval,
    })
}

pub fn validate_native(
    record: &CutexSessionRecord,
    sessions: &CutexSessionStore,
    contract: &ExplicitLaunchContract,
) -> anyhow::Result<PathBuf> {
    ensure!(
        crate::runtime::lifecycle::cutex_session_host_is_local(
            &record.host_id,
            &crate::platform::host::current_host_name()
        ),
        "stock host is not local"
    );
    ensure!(
        record.runtime_backend == CutexSessionRuntimeBackend::Host,
        "stock subset requires existing host backend"
    );
    ensure!(
        record.codex_session_id.as_deref() == Some(&contract.native_id),
        "stock native identity mismatch"
    );
    ensure!(
        sessions
            .sessions
            .values()
            .filter(|r| r.codex_session_id.as_deref() == Some(&contract.native_id))
            .count()
            == 1,
        "ambiguous durable/native mapping"
    );
    ensure!(
        crate::config::paths::host_codex_home_dir()?.canonicalize()? == contract.native_home,
        "stock home is not authoritative native home"
    );
    ensure!(
        !contract.native_home.join("auth.json").try_exists()?,
        "stock private subset does not consume native auth files"
    );
    let mut found = Vec::new();
    let mut pending = vec![contract.native_home.join("sessions")];
    while let Some(dir) = pending.pop() {
        for entry in std::fs::read_dir(dir)? {
            let entry = entry?;
            let ty = entry.file_type()?;
            ensure!(!ty.is_symlink(), "symlinked stock history is unsupported");
            if ty.is_dir() {
                pending.push(entry.path());
            } else if entry
                .file_name()
                .to_string_lossy()
                .ends_with(&format!("{}.jsonl", contract.native_id))
            {
                let path = entry.path();
                canonical(&path)?;
                let first = std::io::BufReader::new(std::fs::File::open(&path)?)
                    .lines()
                    .next()
                    .context("empty native rollout")??;
                let meta: serde_json::Value = serde_json::from_str(&first)?;
                ensure!(
                    meta["type"] == "session_meta" && meta["payload"]["id"] == contract.native_id,
                    "native rollout metadata mismatch"
                );
                found.push(path);
            }
        }
    }
    ensure!(found.len() == 1, "native rollout missing or ambiguous");
    Ok(found.remove(0))
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn stock_shared_config_rejects_execution_auth_and_unknown_options() {
        assert!(validate_shared_config(
            "[analytics]\nenabled=false\n[projects.\"/private\"]\ntrust_level=\"trusted\""
        )
        .is_ok());
        for raw in [
            "notify=['sh','-c','exit 0']",
            "sandbox_mode='danger-full-access'",
            "forced_login_method='chatgpt'",
            "[mcp_servers.foreign]\ncommand='other'",
            "[analytics]\nenabled=true",
            "[projects.x]\ntrust_level='guessed'",
        ] {
            assert!(validate_shared_config(raw).is_err(), "{raw}");
        }
    }
    #[test]
    fn stock_unknown_bundle_fields_and_versions_reject_without_spawn() {
        let json = serde_json::json!({"version":1,"native_id":"not-a-native-id","native_home":"/","bundle_manifest":"/","bundle_sha256":"a".repeat(64)});
        let contract: ExplicitLaunchContract = serde_json::from_value(json.clone()).unwrap();
        assert!(contract.validate().is_err());
        let mut changed = json;
        changed["fallback"] = serde_json::json!("codex");
        assert!(serde_json::from_value::<ExplicitLaunchContract>(changed).is_err());
    }
    #[test]
    fn stock_requirement_survives_runtime_clear_and_serialization() {
        let mut record = CutexSessionRecord::new(
            "cutex.stock".into(),
            Some(uuid::Uuid::new_v4().to_string()),
            "private".into(),
            "/private".into(),
            None,
        )
        .unwrap();
        assert!(crate::agent_management::require_default_launch(&record).is_ok());
        record.explicit_launch = Some(ExplicitLaunchContract {
            version: 999,
            native_id: record.codex_session_id.clone().unwrap(),
            native_home: "/private".into(),
            bundle_manifest: "/private/bundle".into(),
            bundle_sha256: Sha256::new("a".repeat(64)).unwrap(),
        });
        let contract = record.explicit_launch.clone();
        let mut store = CutexSessionStore::default();
        store
            .sessions
            .insert(record.cutex_session_id.clone(), record);
        crate::session::service::clear_cutex_session_runtime_record(
            &mut store,
            "cutex.stock",
            false,
        )
        .unwrap();
        let record = &store.sessions["cutex.stock"];
        assert_eq!(record.explicit_launch, contract);
        assert!(crate::agent_management::require_default_launch(&record).is_err());
        let decoded: CutexSessionRecord =
            serde_json::from_value(serde_json::to_value(&record).unwrap()).unwrap();
        assert_eq!(decoded.explicit_launch, contract);
        crate::session::service::set_cutex_session_profile_by_key(
            &mut store,
            "cutex.stock",
            Some("changed-profile".into()),
        )
        .unwrap();
        let record = store.sessions.get_mut("cutex.stock").unwrap();
        let revision = record.durable_revision();
        crate::session::archive::commit_retire(
            record,
            revision,
            0,
            true,
            "2026-09-09T00:00:00Z".into(),
        )
        .unwrap();
        assert_eq!(record.explicit_launch, contract);
        let revision = record.durable_revision();
        crate::session::archive::commit_restore(record, revision, "2026-09-09T00:00:01Z".into())
            .unwrap();
        assert_eq!(record.explicit_launch, contract);
        assert_eq!(record.profile.as_deref(), Some("changed-profile"));
        assert!(crate::agent_management::require_default_launch(record).is_err());
    }
}
